interval: 20

model: "model/model_b64_e25.pth"

cameras:
  - ["rtsp://cam1:C7XRQPDKbF4JGNRp@192.168.30.147:554/s0", "parkingPlaces.json"]
  - ["rtsp://cam2:C7XRQPDKbF4JGNRp@192.168.30.165:554/s0", "parkingPlaces2.json"]

socket: "testsocket.soc"

ip:
  host: local
  port: 6359